# Uygulama
spring.application.name=twitter
server.port=${PORT:3000}

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/twitter_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1881}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# JWT
jwt.secret=${JWT_SECRET:twitter_secret_key_twitter_secret_key_twitter_secret_key}
jwt.expiration=${JWT_EXPIRATION:86400000}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3200}